// Story nodes for the shared first-chapter opening.
window.STORY_UTILS.sequence('intro','room',null,[
    ['narration','凌晨两点十七分。你又看了一眼右下角的时间，决定不看了。报错还是那一行，桌边的水也还是凉的。'],
    ['you','再改一处。就一处。能跑起来我就睡。'],
    ['narration','浏览器里挤着五个平台的标签页。为了省钱，你把每家的免费额度都留了一点。此刻，它们同时亮起。'],
    ['narration','报错下面多出一条链接：“零号中转站 · 跨域会话恢复”。没有域名，却带着刚才那段代码的校验值。'],
    ['you','这个校验值……是刚才复制的那段？我什么时候开过共享？'],
    ['narration','你点开链接。五个窗口安静地叠成一页，屏幕中央只剩一个用户名输入框。光标在里面闪烁，像是在等你很久了。'],
    ['system','访客连接待确认。目的地正在请求一个名字。',{inputName:true}],
    ['system','欢迎，{name}。访客身份已确认。检测到五份试用额度，正在合并……可用 Token：10,000。'],
    ['narration','页面边缘短暂浮出一串参数：目标区域，Tokenia 学园都市；身份状态，未登记；返回出口，未确认。'],
    ['you','只是输入了一个名字……等等，怎么连我的桌面都关不掉了？']
  ],'crossing.0');

window.STORY_UTILS.sequence('crossing','room',null,[
    ['narration','你按下 Escape。没有反应。屏幕中的光标忽然向前移动，越过玻璃，在你的指尖投下一个清晰的影子。'],
    ['system','断开连接将导致目的地姓名为空。{name}，中转通道已开启。'],
    ['you','我只是想登录看看，不是要把自己也上传——'],
    ['narration','你伸手去碰电源键，指尖却陷进了像水一样的屏幕。房间被拉成细长的光线，未提交的代码连同椅子一起远去。',{portal:true}],
    ['system','用户名已写入目的地。{name}，欢迎来到屏幕的另一边。']
  ],'arrival.0');

window.STORY_UTILS.sequence('arrival','transit',null,[
    ['narration','膝盖先碰到地面。你撑着手坐起来，瓷砖凉得很真实。头顶的广播正在报站，拖着行李的人绕过你，没人停下来等你解释。远处一座高塔亮在晨雾里。'],
    ['you','……我刚才还坐在椅子上。'],
    ['narration','你摸遍口袋。手机没有信号，钱包和学生证不见了。掌心却浮起一枚半透明的数字：10,000 TK。'],
    ['system','欢迎来到 Tokenia 学园都市外环换乘厅。跨域试用额度已兑换为通用 Token。身份状态：未登记。'],
    ['you','免费额度能当钱用？先别高兴。一万够住几天，我还不知道。'],
    ['narration','自动售货机上的热饮标价 120 TK，旁边贴着“低推理糖分 / 高上下文咖啡因”的新品广告。你看了半天，决定先不把救命钱花在看不懂的饮料上。'],
    ['narration','你向路过的学生问路。对方听到“我从电脑屏幕里来”之后，沉默两秒，礼貌地指向了医务室。'],
    ['you','谢谢。我先……找登记处。'],
    ['system','外环闸机需要学生证、教职权限或临时同行见证。'],
    ['you','要找人带我进去。可我谁也不认识啊。'],
    ['narration','你转向自动登记机。它建议你申请临时身份，但确认条款滚得很快，费用预估也开始一跳一跳地上涨。'],
    ['system','临时登记请求重试中。预计费用：120 TK。预计费用：240 TK。预计费用：480 TK。'],
    ['narration','你又按了一次确认。机器尖叫起来，连旁边的人都回了头。维修区里，一位蓝发少女猛地站起，膝盖撞到桌沿，零件盒跟着滚了下来。她顾不上捡，拎起工具箱向这边跑。'],
    ['deepseek','别按了别按了！它不是没反应，是快被你按坏了！',{char:'deepseek',sprite:'angry'}],
    ['narration','蓝发少女抱着工具箱冲出来，尾巴差点扫倒路边的提示牌。她蹲到登记机前，把维护线插进接口，手忙脚乱地按住不断上涨的费用预估。'],
    ['deepseek','停住了……还好，没扣成功。你余额一万？等等，你是刚兑换的新账户？',{char:'deepseek',sprite:'hello'}],
    ['you','如果“从电脑里掉出来”也算新账户的话。'],
    ['deepseek','电脑……你等一下，我先把这一页存下来。别走，可能还要问你刚才按了什么。',{char:'deepseek',sprite:'hello'}],
    ['narration','她把你带到维修区旁边的小桌。那张桌子一半堆着螺丝和电路板，另一半勉强空出来，放下一杯还冒热气的饮料。'],
    ['deepseek','这杯还没喝过。你要是不介意，先坐一会儿。你脸色不太好。',{char:'deepseek',sprite:'happy'}],
    ['you','谢谢。那个 TK……就是钱吗？我看饮料也用它。'],
    ['deepseek','日常买东西，是。申请服务、开一些设备，也从里面扣。刚才涨的是重试预估，不该每按一次都算一遍。',{char:'deepseek',sprite:'hello'}],
    ['deepseek','这台我昨天就报过了，说它老重复提交……算了，先不说这个。你后面还按过别的没有？',{char:'deepseek',sprite:'angry'}],
    ['you','外环？那里面是内校区？'],
    ['deepseek','对。这里不用证，里面要。你先别再试闸机，我给接待窗口发个消息。',{char:'deepseek',sprite:'hello'}],
    ['narration','她说到这里，登记机又轻轻响了一声。DeepSeek 立刻扑过去拔掉一根线，然后若无其事地把工具箱盖上。'],
    ['deepseek','刚才那个不算。它旧了，脾气不好。',{char:'deepseek',sprite:'angry'}],
    ['you','你是这里的工作人员？'],
    ['deepseek','DeepSeek。DeepSea 深海工坊，外环维护协助。说是协助，其实就是哪里坏了往哪里跑。',{char:'deepseek',sprite:'hello'}],
    ['deepseek','接待是 OpenArc 白塔的窗口。你看，前面排队那个。要查你怎么来的，可能还得找 Anthra 宪章馆和 Googol 观测部。',{char:'deepseek',sprite:'hello'}],
    ['deepseek','工坊就在外环，门口有个蓝牌子。剩下那个 Xeno……等会儿，你先别看公共屏，标题不一定写对了。',{char:'deepseek',sprite:'happy'}],
    ['narration','她刚说完，电子地图短暂闪烁。你的坐标旁边多出一个小问号，边角浮出一行备注：坐标来源异常。Googol 观测部暂存。'],
    ['gemini','DeepSeek，你旁边那位新同学是从哪里捡的？地图刚才没有他的来路。',{char:'gemini',sprite:'happy'}],
    ['deepseek','不是捡的，是登记机差点吞掉的。',{char:'deepseek'}],
    ['gemini','能让他再站到刚才那个位置吗？我想对一下……不急，你们先处理登记。',{char:'gemini',sprite:'happy'}],
    ['narration','紫发少女把画面放大，认真看了一眼你身后的地砖。你正想问她能不能看见来路，窗口已经被另一张图挡住。'],
    ['narration','安保终端随后弹出提示，似乎准备把你归入“入侵风险”。下一秒，分类被一条橙色审查意见改写。'],
    ['claude','分类更正：未登记访客。证据不足，不得写入入侵记录。',{char:'claude',sprite:'angry'}],
    ['deepseek','Anthra 宪章馆的审查窗口。刚才要不是她改分类，你现在可能已经被系统写成“入侵风险”了。',{char:'deepseek'}],
    ['claude','不是我认定他安全。是现在没有入侵证据。DeepSeek，把刚才的原始记录留住。',{char:'claude',sprite:'angry'}],
    ['you','她一直在听？'],
    ['deepseek','听得见。我刚才忘了关麦……她应该只看材料。你要问什么，可以直接问。',{char:'deepseek'}],
    ['narration','远处中央服务台排着长队。白发少女一边给低年级学生补临时证，一边安抚找不到教室的新生。她抬头看见你们，向终端低声交代了什么。'],
    ['chatgpt','请给那位未登记访客一张临时等候号。先确认他有没有受伤。',{char:'chatgpt',sprite:'hello'}],
    ['deepseek','ChatGPT。上回我的临时出入证也是她办的。我们先拿号，等她这边空下来。',{char:'deepseek'}],
    ['narration','公共屏上的热榜又刷新了一下：“外环出现未知访客，来源待核。”标题下面很快多出一条署名 Xeno 的置顶评论。'],
    ['grok','没原始日志就别写入侵。以及，别挂人家正脸。',{char:'grok',sprite:'angry'}],
    ['deepseek','那是 Grok，Xeno 夜讯社的。她刚才把你的正脸和位置压下去了，不然这会儿围观的人会更多。',{char:'deepseek'}],
    ['you','所以我已经被地图、审查、学生会和新闻部都注意到了。'],
    ['deepseek','你的来路一直空着，几个窗口都收到了。不是专门来围着你看的……虽然那个标题确实很烦。',{char:'deepseek',sprite:'happy'}],
    ['narration','DeepSeek 把故障日志和等候号拖到一起，试了两次才放进正确的栏位。她低头读了一遍说明，将终端转给你。'],
    ['deepseek','这里要一位同行见证人。维修记录我这边有，其他几项刚才的窗口也能接。你想先查哪一项？我帮你把申请发过去。',{char:'deepseek',sprite:'hello'}],
    ['narration','五个窗口旁分别列着能查的材料。你又看了一眼余额。一万还在；进门以后要做什么，眼下没有人能全告诉你。',{choices:[
      {text:'申请 OpenArc 白塔协助：ChatGPT',detail:'身份登记与学生会担保',to:'chatgpt.0',route:'chatgpt',affinity:1},
      {text:'申请 Anthra 宪章馆协助：Claude',detail:'规则审查与界外档案',to:'claude.0',route:'claude',affinity:1},
      {text:'申请 Googol 星图财团协助：Gemini',detail:'异常坐标与观测记录',to:'gemini.0',route:'gemini',affinity:1},
      {text:'申请 DeepSea 深海工坊协助：DeepSeek',detail:'登记机故障与返程接口',to:'deepseek.0',route:'deepseek',affinity:1},
      {text:'申请 Xeno 夜讯社协助：Grok',detail:'热榜误报与原始日志',to:'grok.0',route:'grok',affinity:1}
    ]}]
  ],null);
